- ckanext/qgov/common/authenticator.py
- this could happen eg when running paster commands before the database is initialised
> [QOL-4495] handle missing tables

- ckanext/qgov/common/anti_csrf.py
- this is necessary for deleting members from organisations
> [QOL-1270] allow query string parameters alongside the CSRF token

- ckanext/qgov/common/anti_csrf.py
This is breaking dataset and resource deletion in Staging, needs to be fixed before we go to production.
> [QOL-5136] don't inject link tokens twice

- ckanext/qgov/common/intercepts.py
- ckanext/qgov/common/plugin.py
This uses a different code path in CKAN 2.8 to CKAN 2.7, so our old patch no longer works.
> [QOL-5426] override 'user_update' action to unlock the account

- README.md
- ckanext/qgov/common/plugin.py
- ckanext/qgov/common/resources/scheming_presets.json
Override the scheming config, if any, to include the resource URL validator in the schema presets.
> Inject URL validator into scheming extensions

- ckanext/qgov/common/plugin.py
- ckanext/qgov/common/test_url_validation.py
- Don't do subdomain matching on IP addresses
- Check resolved DNS aliases, if any
- Memoize address resolution so we don't repeat it for each whitelist/blacklist entry
> Clean up domain matching

- ckanext/qgov/common/intercepts.py
- ckanext/qgov/common/plugin.py
- ckanext/qgov/common/resource_type_validation.py
- ckanext/qgov/common/test_mime_type_validation.py
This should make it easier to review, maintain, and possibly share with others.
> [QOL-7762] refactor - split resource type validation into a separate module

- ckanext/qgov/common/intercepts.py
This controller is associated with Pairtree, and CKAN 2.9 drops it entirely.
> [QOL-7905] skip obsolete StorageController if not present

- ckanext/qgov/common/plugin.py
- The 'search' route needed to be copied from core. This will all go away once we move to CKAN 2.9 and use Flask blueprints, fortunately.
> QOL-7905 Fix search routing bug on CKAN 2.8

- ckanext/qgov/common/plugin.py
Remove functionality to squash author and maintainer information together, which is specific to Open Data and does not belong in this extension.
> Develop to master

- ckanext/qgov/common/views/dataset.py
- Any core routes that match one of our wildcard routes, eg '/dataset/new' matching '/dataset/<id>',
must be repeated in our plugin or else they'll be overridden by the wildcard.
> [QOL-9275] repeat the 'changes_multiple' route definition

- ckanext/qgov/common/authenticator.py
- ckanext/qgov/common/plugin.py
- Use the new IAuthenticator interface, if available, to add our authenticate hook.
> [QOLSVC-978] add CKAN 2.10 support to authenticator

- ckanext/qgov/common/authenticator.py
- ckanext/qgov/common/plugin.py
- test/features/steps/steps.py
Adjust authenticator integration to monkey-patch the original, so that we can prevent the default authentication from working when accounts are locked.
> QOLDEV-313 prepare for CKAN 2.10

- .ahoy.yml
- .docker/test.ini
- .github/workflows/test.yml
- bin/build.sh
- bin/test.sh
- ckanext/qgov/common/authenticator.py
- ckanext/qgov/common/plugin.py
- ckanext/qgov/common/stats.py
- ckanext/qgov/common/views/user.py
- test/features/homepage.feature
- test/features/login_redirect.feature
- test/features/organisations.feature
- test/features/steps/steps.py
- test/features/users.feature
- Drop CKAN 2.8 code as it's no longer supported upstream
- Adjust dashboard tests to handle activity stream plugin split in CKAN 2.10
> QOLDEV-313 support CKAN 2.10 and drop 2.8

- ckanext/qgov/common/helpers.py
- setup.py
- Assume that non-numeric file sizes are already formatted, keep unchanged. This appears to be necessary on CKAN 2.10.
> [QOLDEV-313] make file size formatter more robust

- ckanext/qgov/common/helpers.py
- Treat empty objects as 'no user', the same as None. This appears to be needed on CKAN 2.10.
> [QOLDEV-313] make auth check more robust

- ckanext/qgov/common/plugin.py
- ckanext/qgov/common/resources/scheming_presets.json
- ckanext/qgov/common/templates/admin/config.html
- Replace obsolete string-based validators with proper ones
- Drop obsolete Bootstrap 2 legacy pager
> QOLDEV-313 preparing for CKAN 2.10

- .ahoy.yml
- .github/workflows/test.yml
- bin/create-test-data.sh
- ckanext/qgov/common/views/user.py
- test/features/steps/steps.py
- Inject reCAPTCHA failure message into CKAN 2.10 routing
- Add scenario test
> QOLDEV-455 fix recaptcha failure message on CKAN 2.10

- ckanext/qgov/common/intercepts.py
Plugin was applying the wrong schema to user updates. The update schema is meant to ignore missing passwords, but we were instead applying the default schema.
> QOLDEV-935 fix sysadmin management via web UI

- ckanext/qgov/common/plugin.py
- Don't show the 'dataset not found' flash message if PURL found a target URL.
> QOLDEV-933 remove incorrect error message

- .ahoy.yml
- .env
- .github/workflows/test.yml
- GitHub Actions overrides HOME for unclear reasons, which breaks container expectations, https://github.com/actions/runner/issues/863
> force HOME directory to point at /root

- .github/workflows/test.yml
- bin/build.sh
- ckanext/qgov/common/intercepts.py
- ckanext/qgov/common/views/user.py
- test/features/organisations.feature
- test/features/steps/steps.py
(Our fork of) CKAN 2.11 tests are now required.
> QOLDEV-955 fix testing on CKAN 2.11 and master

- ckanext/qgov/common/helpers.py
Not sure how this wasn't caught in testing earlier.
> [QOLSVC-9300] handle anonymous user objects gracefully
